/**
 * File: db
 *
 * Contains lists of in-game names and their mapping to IDs
 */
import { toGoodKey, toIdedObj } from './helper';
import type { ArtifactSetKey, CharacterKey, StatKey, SubstatKey } from '../types/good';

export const characters: CharacterKey[] = [
	'Amber',
	'Barbara',
	'Beidou',
	'Bennett',
	'Chongyun',
	'Diluc',
	'Fischl',
	'Jean',
	'Kaeya',
	'Keqing',
	'Lisa',
	'Mona',
	'Ningguang',
	'Noelle',
	'Qiqi',
	'Razor',
	'Sucrose',
	'Traveler',
	'Venti',
	'Xiangling',
	'Xingqiu',
	'Klee',
	'Diona',
	'Tartaglia',
	'Xinyan',
	'Zhongli',
	'Albedo',
	'Ganyu',
	'Xiao',
	'HuTao',
	'Rosaria',
	'Yanfei',
	'Eula',
	'KaedeharaKazuha',
	'KamisatoAyaka',
	'Sayu',
	'Yoimiya',
	'Aloy',
	'KujouSara',
	'RaidenShogun',
	'SangonomiyaKokomi',
	'Thoma',
	'AratakiItto',
	'Gorou',
	'Shenhe',
	'YunJin',
	'YaeMiko',
	'KamisatoAyato',
	'Yelan',
	'KukiShinobu',
	'ShikanoinHeizou',
	'Collei',
	'Tighnari',
	'Dori',
	'Candace',
	'Cyno',
	'Nilou',
	'Nahida',
	'Layla',
	'Faruzan',
	'Wanderer',
];
export const artifacts: ArtifactSetKey[] = [
	// 'InitiateLost',
	'Adventurer',
	'LuckyDog',
	'TravelingDoctor',
	'ResolutionOfSojourner',
	'TinyMiracle',
	'Berserker',
	'Instructor',
	'TheExile',
	'DefendersWill',
	'BraveHeart',
	'MartialArtist',
	'Gambler',
	'Scholar',
	'PrayersForWisdom',
	'PrayersForDestiny',
	'PrayersForIllumination',
	'PrayersToSpringtime',
	'GladiatorsFinale',
	'WanderersTroupe',
	'NoblesseOblige',
	'BloodstainedChivalry',
	'MaidenBeloved',
	'ViridescentVenerer',
	'ArchaicPetra',
	'RetracingBolide',
	'Thundersoother',
	'ThunderingFury',
	'Lavawalker',
	'CrimsonWitchOfFlames',
	'BlizzardStrayer',
	'HeartOfDepth',
	'TenacityOfTheMillelith',
	'PaleFlame',
	'ShimenawasReminiscence',
	'EmblemOfSeveredFate',
	'HuskOfOpulentDreams',
	'OceanHuedClam',
	'VermillionHereafter',
	'EchoesOfAnOffering',
	'DeepwoodMemories',
	'GildedDreams',
	'DesertPavilionChronicle',
	'FlowerOfParadiseLost',
];
export const swords = [
	'Aquila Favonia',
	'Freedom-Sworn',
	'Haran Geppaku Futsu',
	'Key of Khaj-Nisut',
	'Mistsplitter Reforged',
	'Primordial Jade Cutter',
	'Skyward Blade',
	'Summit Shaper',
	'Amenoma Kageuchi',
	'Blackcliff Longsword',
	'Cinnabar Spindle',
	'Favonius Sword',
	'Festering Desire',
	'Iron Sting',
	'Kagotsurube Isshin',
	"Lion's Roar",
	'Prized Isshin Blade',
	'Prototype Rancour',
	'Royal Longsword',
	'Sacrificial Sword',
	'Sapwood Blade',
	'Sword of Descension',
	'The Alley Flash',
	'The Black Sword',
	'The Flute',
	'Toukabou Shigure',
	"Xiphos' Moonlight",
	'Cool Steel',
	'Dark Iron Sword',
	'Fillet Blade',
	'Harbinger of Dawn',
	'Skyrider Sword',
	"Traveler's Handy Sword",
	'Silver Sword',
	'Dull Blade',
].map(toGoodKey);
export const claymores = [
	'Redhorn Stonethresher',
	'Skyward Pride',
	'Song of Broken Pines',
	'The Unforged',
	"Wolf's Gravestone",
	'Akuoumaru',
	'Blackcliff Slasher',
	'Favonius Greatsword',
	'Forest Regalia',
	'Katsuragikiri Nagamasa',
	'Lithic Blade',
	'Luxurious Sea-Lord',
	'Makhaira Aquamarine',
	'Prototype Archaic',
	'Rainslasher',
	'Royal Greatsword',
	'Sacrificial Greatsword',
	'Serpent Spine',
	'Snow-Tombed Starsilver',
	'The Bell',
	'Whiteblind',
	'Bloodtainted Greatsword',
	'Debate Club',
	'Ferrous Shadow',
	'Skyrider Greatsword',
	'White Iron Greatsword',
	"Old Merc's Pal",
	'Waster Greatsword',
].map(toGoodKey);
export const polearms = [
	'Calamity Queller',
	'Engulfing Lightning',
	'Primordial Jade Winged-Spear',
	'Skyward Spine',
	'Staff of Homa',
	'Staff of the Scarlet Sands',
	'Vortex Vanquisher',
	'The Catch',
	'Blackcliff Pole',
	'Crescent Pike',
	'Deathmatch',
	"Dragon's Bane",
	'Dragonspine Spear',
	'Favonius Lance',
	'Kitain Cross Spear',
	'Lithic Spear',
	'Missive Windspear',
	'Moonpiercer',
	'Prototype Starglitter',
	'Royal Spear',
	"Wavebreaker's Fin",
	'Black Tassel',
	'Halberd',
	'White Tassel',
	'Iron Point',
	"Beginner's Protector",
].map(toGoodKey);
export const catalysts = [
	'A Thousand Floating Dreams',
	'Everlasting Moonglow',
	"Kagura's Verity",
	'Lost Prayer to the Sacred Winds',
	'Memory of Dust',
	'Skyward Atlas',
	"Tulaytullah's Remembrance",
	'Blackcliff Agate',
	'Dodoco Tales',
	'Eye of Perception',
	'Favonius Codex',
	'Frostbearer',
	'Fruit of Fulfillment',
	'Hakushin Ring',
	'Mappa Mare',
	'Oathsworn Eye',
	'Prototype Amber',
	'Royal Grimoire',
	'Sacrificial Fragments',
	'Solar Pearl',
	'The Widsith',
	'Wandering Evenstar',
	'Wine and Song',
	'Emerald Orb',
	'Magic Guide',
	'Otherworldly Story',
	'Thrilling Tales of Dragon Slayers',
	'Twin Nephrite',
	'Pocket Grimoire',
	"Apprentice's Notes",
].map(toGoodKey);
export const bows = [
	"Amos' Bow",
	'Aqua Simulacra',
	'Elegy for the End',
	"Hunter's Path",
	'Polar Star',
	'Skyward Harp',
	'Thundering Pulse',
	'Alley Hunter',
	'Blackcliff Warbow',
	'Compound Bow',
	'End of the Line',
	'Fading Twilight',
	'Favonius Warbow',
	'Hamayumi',
	"King's Squire",
	'Mitternachts Waltz',
	"Mouun's Moon",
	'Predator',
	'Prototype Crescent',
	'Royal Bow',
	'Rust',
	'Sacrificial Bow',
	'The Stringless',
	'The Viridescent Hunt',
	'Windblume Ode',
	'Messenger',
	'Raven Bow',
	'Recurve Bow',
	"Sharpshooter's Oath",
	'Slingshot',
	"Seasoned Hunter's Bow",
	"Hunter's Bow",
].map(toGoodKey);

export const artifactMS: StatKey[] = [
	'hp', //HP
	'hp_', //HP%
	'atk', //ATK
	'atk_', //ATK%
	'def', //DEF
	'def_', //DEF%
	'eleMas', //Elemental Mastery
	'enerRech_', //Energy Recharge
	'heal_', //Healing Bonus
	'critRate_', //Crit Rate
	'critDMG_', //Crit DMG
	'physical_dmg_', //Physical DMG Bonus
	'anemo_dmg_', //Anemo DMG Bonus
	'geo_dmg_', //Geo DMG Bonus
	'electro_dmg_', //Electro DMG Bonus
	'hydro_dmg_', //Hydro DMG Bonus
	'pyro_dmg_', //Pyro DMG Bonus
	'cryo_dmg_', //Cryo DMG Bonus
	'dendro_dmg_', //Dendro DMG Bonus
];

export const artifactSS: (SubstatKey | '_')[] = [
	'_',
	'hp', //HP
	'hp_', //HP%
	'atk', //ATK
	'atk_', //ATK%
	'def', //DEF
	'def_', //DEF%
	'eleMas', //Elemental Mastery
	'enerRech_', //Energy Recharge
	'critRate_', //Crit Rate
	'critDMG_', //Crit DMG
];

export const characterIDs = toIdedObj(characters);
export const artifactIDs = toIdedObj(artifacts);
export const swordIDs = toIdedObj(swords);
export const claymoreIDs = toIdedObj(claymores);
export const polearmIDs = toIdedObj(polearms);
export const catalystIDs = toIdedObj(catalysts);
export const bowIDs = toIdedObj(bows);
export const artifactMSIDs = toIdedObj(artifactMS);
export const artifactSSIDs = toIdedObj(artifactSS);

export const characterWeapons: { [key in CharacterKey]: string[] } = {
	Amber: bows,
	Barbara: catalysts,
	Beidou: claymores,
	Bennett: swords,
	Chongyun: claymores,
	Diluc: claymores,
	Fischl: bows,
	Jean: swords,
	Kaeya: swords,
	Keqing: swords,
	Lisa: catalysts,
	Mona: catalysts,
	Ningguang: catalysts,
	Noelle: claymores,
	Qiqi: swords,
	Razor: claymores,
	Sucrose: catalysts,
	Traveler: swords,
	Venti: bows,
	Xiangling: polearms,
	Xingqiu: swords,
	Klee: catalysts,
	Diona: bows,
	Tartaglia: bows,
	Xinyan: claymores,
	Zhongli: polearms,
	Albedo: swords,
	Ganyu: bows,
	Xiao: polearms,
	HuTao: polearms,
	Rosaria: polearms,
	Yanfei: catalysts,
	Eula: claymores,
	KaedeharaKazuha: swords,
	KamisatoAyaka: swords,
	Sayu: claymores,
	Yoimiya: bows,
	Aloy: bows,
	KujouSara: bows,
	RaidenShogun: polearms,
	SangonomiyaKokomi: catalysts,
	Thoma: polearms,
	AratakiItto: claymores,
	Gorou: bows,
	Shenhe: polearms,
	YunJin: polearms,
	YaeMiko: catalysts,
	KamisatoAyato: swords,
	Yelan: bows,
	KukiShinobu: swords,
	ShikanoinHeizou: catalysts,
	Collei: bows,
	Tighnari: bows,
	Dori: claymores,
	Candace: polearms,
	Cyno: polearms,
	Nilou: swords,
	Nahida: catalysts,
	Layla: swords,
	Faruzan: bows,
	Wanderer: catalysts,
};

export const characterWeaponIDs: { [key in CharacterKey]: { [key: string]: number } } = {
	Amber: bowIDs,
	Barbara: catalystIDs,
	Beidou: claymoreIDs,
	Bennett: swordIDs,
	Chongyun: claymoreIDs,
	Diluc: claymoreIDs,
	Fischl: bowIDs,
	Jean: swordIDs,
	Kaeya: swordIDs,
	Keqing: swordIDs,
	Lisa: catalystIDs,
	Mona: catalystIDs,
	Ningguang: catalystIDs,
	Noelle: claymoreIDs,
	Qiqi: swordIDs,
	Razor: claymoreIDs,
	Sucrose: catalystIDs,
	Traveler: swordIDs,
	Venti: bowIDs,
	Xiangling: polearmIDs,
	Xingqiu: swordIDs,
	Klee: catalystIDs,
	Diona: bowIDs,
	Tartaglia: bowIDs,
	Xinyan: claymoreIDs,
	Zhongli: polearmIDs,
	Albedo: swordIDs,
	Ganyu: bowIDs,
	Xiao: polearmIDs,
	HuTao: polearmIDs,
	Rosaria: polearmIDs,
	Yanfei: catalystIDs,
	Eula: claymoreIDs,
	KaedeharaKazuha: swordIDs,
	KamisatoAyaka: swordIDs,
	Sayu: claymoreIDs,
	Yoimiya: bowIDs,
	Aloy: bowIDs,
	KujouSara: bowIDs,
	RaidenShogun: polearmIDs,
	SangonomiyaKokomi: catalystIDs,
	Thoma: polearmIDs,
	AratakiItto: claymoreIDs,
	Gorou: bowIDs,
	Shenhe: polearmIDs,
	YunJin: polearmIDs,
	YaeMiko: catalystIDs,
	KamisatoAyato: swordIDs,
	Yelan: bowIDs,
	KukiShinobu: swordIDs,
	ShikanoinHeizou: catalystIDs,
	Collei: bowIDs,
	Tighnari: bowIDs,
	Dori: claymoreIDs,
	Candace: polearmIDs,
	Cyno: polearmIDs,
	Nilou: swordIDs,
	Nahida: catalystIDs,
	Layla: swordIDs,
	Faruzan: bowIDs,
	Wanderer: catalystIDs,
};
